### ISSUE TITLE
Thinking Matters variation admin bar missing links

### ISSUE THREAD

**Issue by marpa** [clas-web/news-hub-uncc#22]
Thinking Matters variation admin bar should have a link labelled College of Liberal Arts & Sciences that is display to the right of the UNC Charlotte logo when NOT logged in, compare:
https://clas-pages.uncc.edu/
https://thinkingmatters.uncc.edu

**Comment by marpa** [comment]
Don't forget to to fix this issue.

**Comment by atrus1701** [comment]
d88b17d1cfa21cfffb0c715f8dab52791d9e991d
